import SwiftUI

/// ResPilot's mark: a compass ring with a lightning-bolt needle through it —
/// original vector artwork drawn from primitives (a stroked `Circle` plus a
/// hand-built bolt `Path`), not a bundled raster asset. Scales cleanly from
/// a toolbar glyph up to the sidebar header without a separate image asset
/// pipeline, and matches the same silhouette baked into the app icon
/// (`Scripts/AppIcon.icns`, generated by the same bolt geometry).
struct ResPilotMark: View {
    var size: CGFloat = 28
    var color: Color = .white

    var body: some View {
        ZStack {
            Circle()
                .stroke(color, lineWidth: max(1.5, size * 0.075))
            BoltShape()
                .fill(color)
                .frame(width: size * 0.44, height: size * 0.7)
                .rotationEffect(.degrees(-20))
        }
        .frame(width: size, height: size)
    }
}

/// The bolt silhouette, normalized to a 0...140x0...320 bounding box so it
/// drops into any frame via `.aspectRatio(contentMode: .fit)`-style scaling.
private struct BoltShape: Shape {
    func path(in rect: CGRect) -> Path {
        let points: [CGPoint] = [
            CGPoint(x: 0.64, y: 1.0),
            CGPoint(x: 0.0, y: 0.53),
            CGPoint(x: 0.39, y: 0.53),
            CGPoint(x: 0.18, y: 0.0),
            CGPoint(x: 1.0, y: 0.5),
            CGPoint(x: 0.57, y: 0.5),
        ].map { CGPoint(x: $0.x * rect.width, y: (1 - $0.y) * rect.height) }

        var path = Path()
        path.addLines(points)
        path.closeSubpath()
        return path
    }
}

/// Icon + wordmark lockup for the sidebar header.
struct ResPilotWordmark: View {
    var markSize: CGFloat = 26
    var fontSize: CGFloat = 19
    var color: Color = .white

    var body: some View {
        HStack(spacing: 10) {
            ResPilotMark(size: markSize, color: color)
            Text("ResPilot")
                .font(.system(size: fontSize, weight: .semibold, design: .rounded))
                .foregroundStyle(color)
        }
    }
}
